/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAuthTrendingRouteImport } from './routes/_auth/_auth.trending'
import { Route as AuthAuthSettingsRouteImport } from './routes/_auth/_auth.settings'
import { Route as AuthAuthCreatePostRouteImport } from './routes/_auth/_auth.create-post'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthTrendingRoute = AuthAuthTrendingRouteImport.update({
  id: '/_auth/trending',
  path: '/trending',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthSettingsRoute = AuthAuthSettingsRouteImport.update({
  id: '/_auth/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthCreatePostRoute = AuthAuthCreatePostRouteImport.update({
  id: '/_auth/create-post',
  path: '/create-post',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/hello': typeof HelloRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-post': typeof AuthAuthCreatePostRoute
  '/settings': typeof AuthAuthSettingsRoute
  '/trending': typeof AuthAuthTrendingRoute
}
export interface FileRoutesByTo {
  '/hello': typeof HelloRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthIndexRoute
  '/create-post': typeof AuthAuthCreatePostRoute
  '/settings': typeof AuthAuthSettingsRoute
  '/trending': typeof AuthAuthTrendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/hello': typeof HelloRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/_auth/create-post': typeof AuthAuthCreatePostRoute
  '/_auth/_auth/settings': typeof AuthAuthSettingsRoute
  '/_auth/_auth/trending': typeof AuthAuthTrendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hello'
    | '/login'
    | '/register'
    | '/create-post'
    | '/settings'
    | '/trending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hello'
    | '/login'
    | '/register'
    | '/'
    | '/create-post'
    | '/settings'
    | '/trending'
  id:
    | '__root__'
    | '/_auth'
    | '/hello'
    | '/login'
    | '/register'
    | '/_auth/'
    | '/_auth/_auth/create-post'
    | '/_auth/_auth/settings'
    | '/_auth/_auth/trending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HelloRoute: typeof HelloRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_auth/trending': {
      id: '/_auth/_auth/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthAuthTrendingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_auth/settings': {
      id: '/_auth/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthAuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_auth/create-post': {
      id: '/_auth/_auth/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof AuthAuthCreatePostRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAuthCreatePostRoute: typeof AuthAuthCreatePostRoute
  AuthAuthSettingsRoute: typeof AuthAuthSettingsRoute
  AuthAuthTrendingRoute: typeof AuthAuthTrendingRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAuthCreatePostRoute: AuthAuthCreatePostRoute,
  AuthAuthSettingsRoute: AuthAuthSettingsRoute,
  AuthAuthTrendingRoute: AuthAuthTrendingRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HelloRoute: HelloRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
